Update NOTICE

diff --git a/NOTICE b/NOTICE
--- a/NOTICE
+++ b/NOTICE
@@ -1,259 +1,45 @@
-zentity
-Copyright © 2018-2021 Dave Moore
-https://zentity.io
-
-Licensed under the Apache License, Version 2.0 (the "License");
-you may not use this file except in compliance with the License.
-You may obtain a copy of the License at
-
-    http://www.apache.org/licenses/LICENSE-2.0
-
-Unless required by applicable law or agreed to in writing, software
-distributed under the License is distributed on an "AS IS" BASIS,
-WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-See the License for the specific language governing permissions and
-limitations under the License.
-
-================================================================================
-
-zentity uses the following third-party dependencies:
-
---------------------------------------------------------------------------------
-
-Name:     HPPC Collections
-Artifact: com.carrotsearch:hppc:0.8.1
-URL:      http://labs.carrotsearch.com/hppc.html/hppc
-License:  The Apache Software License, Version 2.0
-
---------------------------------------------------------------------------------
-
-Name:     Jackson-annotations
-Artifact: com.fasterxml.jackson.core:jackson-annotations:2.10.5
-URL:      http://github.com/FasterXML/jackson
-License:  The Apache Software License, Version 2.0
-
---------------------------------------------------------------------------------
-
-Name:     Jackson-core
-Artifact: com.fasterxml.jackson.core:jackson-core:2.10.5
-URL:      https://github.com/FasterXML/jackson-core
-License:  The Apache Software License, Version 2.0
-
---------------------------------------------------------------------------------
-
-Name:     jackson-databind
-Artifact: com.fasterxml.jackson.core:jackson-databind:2.10.5.1
-URL:      http://github.com/FasterXML/jackson
-License:  The Apache Software License, Version 2.0
-
---------------------------------------------------------------------------------
-
-Name:     Jackson dataformat: CBOR
-Artifact: com.fasterxml.jackson.dataformat:jackson-dataformat-cbor:2.10.4
-URL:      http://github.com/FasterXML/jackson-dataformats-binary
-License:  The Apache Software License, Version 2.0
-
---------------------------------------------------------------------------------
-
-Name:     Jackson dataformat: Smile
-Artifact: com.fasterxml.jackson.dataformat:jackson-dataformat-smile:2.10.4
-URL:      http://github.com/FasterXML/jackson-dataformats-binary
-License:  The Apache Software License, Version 2.0
-
---------------------------------------------------------------------------------
-
-Name:     Jackson-dataformat-YAML
-Artifact: com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.10.4
-URL:      https://github.com/FasterXML/jackson-dataformats-text
-License:  The Apache Software License, Version 2.0
-
---------------------------------------------------------------------------------
-
-Name:     T-Digest
-Artifact: com.tdunning:t-digest:3.2
-URL:      https://github.com/tdunning/t-digest
-License:  The Apache Software License, Version 2.0
-
---------------------------------------------------------------------------------
-
-Name:     Joda-Time
-Artifact: joda-time:joda-time:2.10.4
-URL:      https://www.joda.org/joda-time/
-License:  Apache License, Version 2.0
-
---------------------------------------------------------------------------------
-
-Name:     JOpt Simple
-Artifact: net.sf.jopt-simple:jopt-simple:5.0.2
-URL:      http://pholser.github.io/jopt-simple
-License:  The MIT License
-
---------------------------------------------------------------------------------
-
-Name:     Apache Log4j API
-Artifact: org.apache.logging.log4j:log4j-api:2.11.1
-URL:      https://logging.apache.org/log4j/2.x/log4j-api/
-License:  Apache License, Version 2.0
-
---------------------------------------------------------------------------------
-
-Name:     Lucene Common Analyzers
-Artifact: org.apache.lucene:lucene-analyzers-common:8.5.1
-URL:      https://lucene.apache.org/lucene-parent/lucene-analyzers-common
-License:  Apache 2
-
---------------------------------------------------------------------------------
-
-Name:     Lucene Memory
-Artifact: org.apache.lucene:lucene-backward-codecs:8.5.1
-URL:      https://lucene.apache.org/lucene-parent/lucene-backward-codecs
-License:  Apache 2
-
---------------------------------------------------------------------------------
-
-Name:     Lucene Core
-Artifact: org.apache.lucene:lucene-core:8.5.1
-URL:      https://lucene.apache.org/lucene-parent/lucene-core
-License:  Apache 2
-
---------------------------------------------------------------------------------
-
-Name:     Lucene Grouping
-Artifact: org.apache.lucene:lucene-grouping:8.5.1
-URL:      https://lucene.apache.org/lucene-parent/lucene-grouping
-License:  Apache 2
-
---------------------------------------------------------------------------------
-
-Name:     Lucene Highlighter
-Artifact: org.apache.lucene:lucene-highlighter:8.5.1
-URL:      https://lucene.apache.org/lucene-parent/lucene-highlighter
-License:  Apache 2
-
---------------------------------------------------------------------------------
-
-Name:     Lucene Join
-Artifact: org.apache.lucene:lucene-join:8.5.1
-URL:      https://lucene.apache.org/lucene-parent/lucene-join
-License:  Apache 2
-
---------------------------------------------------------------------------------
-
-Name:     Lucene Memory
-Artifact: org.apache.lucene:lucene-memory:8.5.1
-URL:      https://lucene.apache.org/lucene-parent/lucene-memory
-License:  Apache 2
-
---------------------------------------------------------------------------------
-
-Name:     Lucene Miscellaneous
-Artifact: org.apache.lucene:lucene-misc:8.5.1
-URL:      https://lucene.apache.org/lucene-parent/lucene-misc
-License:  Apache 2
-
---------------------------------------------------------------------------------
-
-Name:     Lucene Queries
-Artifact: org.apache.lucene:lucene-queries:8.5.1
-URL:      https://lucene.apache.org/lucene-parent/lucene-queries
-License:  Apache 2
-
---------------------------------------------------------------------------------
-
-Name:     Lucene QueryParsers
-Artifact: org.apache.lucene:lucene-queryparser:8.5.1
-URL:      https://lucene.apache.org/lucene-parent/lucene-queryparser
-License:  Apache 2
-
---------------------------------------------------------------------------------
-
-Name:     Lucene Sandbox
-Artifact: org.apache.lucene:lucene-sandbox:8.5.1
-URL:      https://lucene.apache.org/lucene-parent/lucene-sandbox
-License:  Apache 2
-
---------------------------------------------------------------------------------
-
-Name:     Lucene Spatial Extras
-Artifact: org.apache.lucene:lucene-spatial-extras:8.5.1
-URL:      https://lucene.apache.org/lucene-parent/lucene-spatial-extras
-License:  Apache 2
-
---------------------------------------------------------------------------------
-
-Name:     Lucene Spatial 3D
-Artifact: org.apache.lucene:lucene-spatial3d:8.5.1
-URL:      https://lucene.apache.org/lucene-parent/lucene-spatial3d
-License:  Apache 2
-
---------------------------------------------------------------------------------
-
-Name:     Lucene Suggest
-Artifact: org.apache.lucene:lucene-suggest:8.5.1
-URL:      https://lucene.apache.org/lucene-parent/lucene-suggest
-License:  Apache 2
-
---------------------------------------------------------------------------------
-
-Name:     server
-Artifact: org.elasticsearch:elasticsearch:7.8.1
-URL:      https://github.com/elastic/elasticsearch
-License:  The Apache Software License, Version 2.0
-
---------------------------------------------------------------------------------
-
-Name:     elasticsearch-cli
-Artifact: org.elasticsearch:elasticsearch-cli:7.8.1
-URL:      https://github.com/elastic/elasticsearch
-License:  The Apache Software License, Version 2.0
-
---------------------------------------------------------------------------------
-
-Name:     elasticsearch-core
-Artifact: org.elasticsearch:elasticsearch-core:7.8.1
-URL:      https://github.com/elastic/elasticsearch
-License:  The Apache Software License, Version 2.0
-
---------------------------------------------------------------------------------
-
-Name:     elasticsearch-geo
-Artifact: org.elasticsearch:elasticsearch-geo:7.8.1
-URL:      https://github.com/elastic/elasticsearch
-License:  The Apache Software License, Version 2.0
-
---------------------------------------------------------------------------------
-
-Name:     elasticsearch-secure-sm
-Artifact: org.elasticsearch:elasticsearch-secure-sm:7.8.1
-URL:      https://github.com/elastic/elasticsearch
-License:  The Apache Software License, Version 2.0
-
---------------------------------------------------------------------------------
-
-Name:     elasticsearch-x-content
-Artifact: org.elasticsearch:elasticsearch-x-content:7.8.1
-URL:      https://github.com/elastic/elasticsearch
-License:  The Apache Software License, Version 2.0
-
---------------------------------------------------------------------------------
-
-Name:     Elastic JNA Distribution
-Artifact: org.elasticsearch:jna:5.5.0
-URL:      https://github.com/java-native-access/jna
-License:  Apache License, Version 2.0
-
---------------------------------------------------------------------------------
-
-Name:     HdrHistogram
-Artifact: org.hdrhistogram:HdrHistogram:2.1.9
-URL:      http://hdrhistogram.github.io/HdrHistogram/
-License:  Public Domain, per Creative Commons CC0
-
---------------------------------------------------------------------------------
-
-Name:     SnakeYAML
-Artifact: org.yaml:snakeyaml:1.26
-URL:      http://www.snakeyaml.org
-License:  Apache License, Version 2.0
-
---------------------------------------------------------------------------------
+#!/bin/bash
+
+# SonarQube URL (Update as necessary)
+SONARQUBE_URL=""
+
+# Authentication details
+AUTH_TOKEN=""
+
+# Project key and branch name
+PROJECT_KEY=""
+BRANCH_NAME=""
+
+# API endpoint for updating the New Code settings
+NEW_CODE_API="t"
+
+# Set reference branch for New Code to master
+echo "Starting New Code configuration for project $PROJECT_KEY on branch $BRANCH_NAME"
+
+# Execute the API request
+curl -v -u "$AUTH_TOKEN:" -X POST "$NEW_CODE_API" \
+     -d "project=$PROJECT_KEY" \
+     -d "branch=$BRANCH_NAME" \
+     -d "type=REFERENCE_BRANCH" \
+     -d "" \
+     -o response.json -w "%{http_code}"
+
+# Check if the API request was successful
+if [[ $? -eq 0 ]]; then
+  echo "API request sent successfully."
+else
+  echo "Failed to send API request."
+  exit 1
+fi
+
+# Parse and display the response
+RESPONSE_CODE=$(cat response.json | jq -r '.http_code')
+if [[ "$RESPONSE_CODE" == "200" ]]; then
+  echo "New Code setting updated successfully for project $PROJECT_KEY."
+else
+  echo "Failed to update New Code setting. HTTP response code: $RESPONSE_CODE"
+  cat response.json  # Display the full response for debugging
+fi
+
+# Clean up
+rm response.json
